# @package _group_
model:
  _target_: sklearn.linear_model.ElasticNet
search_ranges:
  alpha:
    type: "float"
    low: 1e-4
    high: 1
    log: True
  l1_ratio:
    type: "float"
    low: 1e-4
    high: 1
    log: True
random_state: 5
