# @package _group_
model:
  _target_: sklearn.linear_model.ElasticNet
search_ranges:
  alpha:
    type: "float"
    low: 1e-4
    high: 1
    log: True
  l1_ratio:
    type: "float"
    low: 1e-4
    high: 1
    log: True
  example_int:
    type: "int"
    low: 1
    high: 5
  example_categorical:
    type: "categorical"
    choices:
      - "Hello"
      - "Goodbye"
      - "Au revoir"
      - "Bonjour"
 random_state: 5
